# FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim
FROM python:3.9-slim

WORKDIR /build

# Install zip
RUN apt-get update && apt-get install -y zip

# Copy Cloud Function
COPY workloads/gcp/http_function.py .

# Create the zip
RUN zip function.zip http_function.py